### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by trygve-lie**
This project is lacking a license. Due to this it hard to for us to use this module in our enterprise SoMe tool chain.

Please fix!

### CODE REVIEW

**Comment by leftieFriele** [comment]
I definitely think our legal expert @digitalsadhu needs to look more into this before we merge.

**Comment by yoshuawuyts** [comment]
Is this compatible with [license-server](https://www.npmjs.com/package/license-server) for on-premise license hosting?

**Comment by digitalsadhu** [comment]
I make it a habit to never read PRs before merge so bottoms up!

**Comment by trygve-lie** [comment]
:clap: bro!

**Comment by digitalsadhu** [comment]
@yoshuawuyts err.. yes. Must be... I assume.

**Pull request merged**
